### ISSUE TITLE
This WARN with NullPointer occurs when the app starts

### ISSUE THREAD

**Issue by casevictor** [ricardoalcocer/actionbarextras#64]
```
[WARN]  W/System.err: java.lang.NullPointerException
[WARN]  W/System.err: 	at com.alcoapps.actionbarextras.ActionbarextrasModule.handleSetMenuItemIcon(ActionbarextrasModule.java:527)
[WARN]  W/System.err: 	at com.alcoapps.actionbarextras.ActionbarextrasModule.handleMessage(ActionbarextrasModule.java:158)
[WARN]  W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[WARN]  W/System.err: 	at android.os.Looper.loop(Looper.java:137)
[WARN]  W/System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5103)
[WARN]  W/System.err: 	at java.lang.reflect.Method.invokeNative(Native Method)
[WARN]  W/System.err: 	at java.lang.reflect.Method.invoke(Method.java:525)
[WARN]  W/System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
[WARN]  W/System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
[WARN]  W/System.err: 	at dalvik.system.NativeStart.main(Native Method)
[WARN]  W/System.err: java.lang.NullPointerException
[WARN]  W/System.err: 	at com.alcoapps.actionbarextras.ActionbarextrasModule.handleSetMenuItemIcon(ActionbarextrasModule.java:527)
[WARN]  W/System.err: 	at com.alcoapps.actionbarextras.ActionbarextrasModule.handleMessage(ActionbarextrasModule.java:158)
[WARN]  W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[WARN]  W/System.err: 	at android.os.Looper.loop(Looper.java:137)
[WARN]  W/System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5103)
[WARN]  W/System.err: 	at java.lang.reflect.Method.invokeNative(Native Method)
[WARN]  W/System.err: 	at java.lang.reflect.Method.invoke(Method.java:525)
[WARN]  W/System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
[WARN]  W/System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
[WARN]  W/System.err: 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by manumaticx** [comment]
@casevictor thanks for the report. does this happen using the [example code](https://github.com/ricardoalcocer/actionbarextras/blob/master/example/Resources/app.js)?
