### ISSUE TITLE
NULL pointers with Allloy 1.5.1 and Ti SDK 3.5.1

### ISSUE THREAD

**Issue by tkrz** [ricardoalcocer/actionbarextras#67]
It seems that module has some problems on latest Alloy and Ti SDK. According to documentation this should work:
```javascript
_abx = require('com.alcoapps.actionbarextras');
_abx.setBackgroundColor("#ffffff");
_abx.title = "wewfwefwe";
_abx.hideLogo();
````
But in console, while window opens i can see those errors: 
````
[WARN] :   W/System.err: java.lang.NullPointerException
[WARN] :   W/System.err:    at com.alcoapps.actionbarextras.ActionbarextrasModule.handleSetBackgroundColor(ActionbarextrasModule.java:261)
[WARN] :   W/System.err:    at com.alcoapps.actionbarextras.ActionbarextrasModule.handleMessage(ActionbarextrasModule.java:126)
[WARN] :   W/System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
[WARN] :   W/System.err:    at android.os.Looper.loop(Looper.java:136)
[WARN] :   W/System.err:    at android.app.ActivityThread.main(ActivityThread.java:5196)
[WARN] :   W/System.err:    at java.lang.reflect.Method.invokeNative(Native Method)
[WARN] :   W/System.err:    at java.lang.reflect.Method.invoke(Method.java:515)
[WARN] :   W/System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
[WARN] :   W/System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
[WARN] :   W/System.err:    at dalvik.system.NativeStart.main(Native Method)
[WARN] :   W/System.err: java.lang.NullPointerException
[WARN] :   W/System.err:    at com.alcoapps.actionbarextras.ActionbarextrasModule.handleSetTitle(ActionbarextrasModule.java:190)
[WARN] :   W/System.err:    at com.alcoapps.actionbarextras.ActionbarextrasModule.handleMessage(ActionbarextrasModule.java:118)
[WARN] :   W/System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
[WARN] :   W/System.err:    at android.os.Looper.loop(Looper.java:136)
[WARN] :   W/System.err:    at android.app.ActivityThread.main(ActivityThread.java:5196)
[WARN] :   W/System.err:    at java.lang.reflect.Method.invokeNative(Native Method)
[WARN] :   W/System.err:    at java.lang.reflect.Method.invoke(Method.java:515)
[WARN] :   W/System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
[WARN] :   W/System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
[WARN] :   W/System.err:    at dalvik.system.NativeStart.main(Native Method)
[WARN] :   W/System.err: java.lang.NullPointerException
[WARN] :   W/System.err:    at com.alcoapps.actionbarextras.ActionbarextrasModule.handleHideLogo(ActionbarextrasModule.java:544)
[WARN] :   W/System.err:    at com.alcoapps.actionbarextras.ActionbarextrasModule.handleMessage(ActionbarextrasModule.java:162)
[WARN] :   W/System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
[WARN] :   W/System.err:    at android.os.Looper.loop(Looper.java:136)
[WARN] :   W/System.err:    at android.app.ActivityThread.main(ActivityThread.java:5196)
[WARN] :   W/System.err:    at java.lang.reflect.Method.invokeNative(Native Method)
[WARN] :   W/System.err:    at java.lang.reflect.Method.invoke(Method.java:515)
[WARN] :   W/System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
[WARN] :   W/System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
[WARN] :   W/System.err:    at dalvik.system.NativeStart.main(Native Method)
````
Ti SDK 3.5.1
Alloy 1.5.1
Android device 4.4.4, emulator 5.1.0

**Comment by manumaticx** [comment]
Hm, I'm not able to reproduce this... Are you using v1.6.2 ? Can you run the [example app](https://github.com/ricardoalcocer/actionbarextras/tree/master/example) with your environment?

**Comment by ricardoalcocer** [comment]
@tkrz , please make sure you're setting it up in the "open" event of the Window: 

https://github.com/ricardoalcocer/actionbarextras/blob/master/example/Resources/app.js#L120

R

**Comment by manumaticx** [comment]
I added a hint to the docs.

@tkrz Please let me know, if this solved your issue.

**Comment by tkrz** [comment]
Yes, i have called those methods before my win was open... I didn't realized that this works similar to Ti.Android.Actionbar. I will change this tomorrow, and confirm results.

**Comment by ricardoalcocer** [comment]
User confirmed by email that it's now working after calling the module from the "open" event.
