### ISSUE TITLE
handleSetMenuItemIcon doesn't parse hex values

### ISSUE THREAD

**Issue by manumaticx** [ricardoalcocer/actionbarextras#70]
If you pass `icon: 0xf002` to `setMenuItemIcon( )` you'll get this error:

```
05-27 11:28:51.261: W/System.err(12623): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
05-27 11:28:51.261: W/System.err(12623): 	at com.alcoapps.actionbarextras.ActionbarextrasModule.handleSetMenuItemIcon(ActionbarextrasModule.java:518)
05-27 11:28:51.261: W/System.err(12623): 	at com.alcoapps.actionbarextras.ActionbarextrasModule.handleMessage(ActionbarextrasModule.java:158)
05-27 11:28:51.261: W/System.err(12623): 	at android.os.Handler.dispatchMessage(Handler.java:98)
05-27 11:28:51.261: W/System.err(12623): 	at android.os.Looper.loop(Looper.java:135)
05-27 11:28:51.261: W/System.err(12623): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
05-27 11:28:51.261: W/System.err(12623): 	at java.lang.reflect.Method.invoke(Native Method)
05-27 11:28:51.261: W/System.err(12623): 	at java.lang.reflect.Method.invoke(Method.java:372)
05-27 11:28:51.262: W/System.err(12623): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
05-27 11:28:51.262: W/System.err(12623): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
05-27 11:28:51.263: W/System.err(12623): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
05-27 11:28:51.265: W/System.err(12623): 	at com.alcoapps.actionbarextras.ActionbarextrasModule.handleSetMenuItemIcon(ActionbarextrasModule.java:518)
05-27 11:28:51.265: W/System.err(12623): 	at com.alcoapps.actionbarextras.ActionbarextrasModule.handleMessage(ActionbarextrasModule.java:158)
05-27 11:28:51.265: W/System.err(12623): 	at android.os.Handler.dispatchMessage(Handler.java:98)
05-27 11:28:51.265: W/System.err(12623): 	at android.os.Looper.loop(Looper.java:135)
05-27 11:28:51.265: W/System.err(12623): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
05-27 11:28:51.265: W/System.err(12623): 	at java.lang.reflect.Method.invoke(Native Method)
05-27 11:28:51.265: W/System.err(12623): 	at java.lang.reflect.Method.invoke(Method.java:372)
05-27 11:28:51.265: W/System.err(12623): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
05-27 11:28:51.265: W/System.err(12623): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

It should actually parse the hex value to a valid unicode char.

**Comment by manumaticx** [comment]
Closing this again as this is not a bug. The module does work fine.
This error was a mistake by me. You should not pass a hex number but a string like this:
```js
icon: String.fromCharCode(0xf002)
```
